// Export all skeleton components for easy importing
export { default as SkeletonBase } from './SkeletonBase';
export { default as SkeletonHero } from './SkeletonHero';
export { default as SkeletonStatsGrid } from './SkeletonStatsGrid';
export { default as SkeletonCards } from './SkeletonCards';
export { default as SkeletonTable } from './SkeletonTable';
export { default as SkeletonForm } from './SkeletonForm';
export { default as SkeletonButton } from './SkeletonButton';
export { default as SkeletonList } from './SkeletonList';
export { default as SkeletonDashboard } from './SkeletonDashboard';
export { default as SkeletonPage } from './SkeletonPage';